---
resources:
- name: service-sql-repo
  type: git
  source:
    uri: https://github.com/EMC-Underground/service_sql.git
    branch: master

jobs:
  - name: update-service-sql-pipeline
    public: true
    plan:
      - get: service-sql-repo
        trigger: true
      - task: update-pipeline
        params:
          CONCOURSE_USERNAME: ((concourse_username))
          CONCOURSE_PASSWORD: ((concourse_password))
          CONCOURSE_URL: ((concourse_url))
          VAULT_ADDR: ((vault_addr))
          VAULT_TOKEN: ((root_token))
        config:
          inputs:
            - name: service-sql-repo
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: starkandwayne/concourse
              tag: latest
          run:
            path: sh
            args:
            - -c
            - |
              fly -t main login -u ${CONCOURSE_USERNAME} -p ${CONCOURSE_PASSWORD} -c ${CONCOURSE_URL}
              fly -t main sync
              cd ./service-sql-repo
              fly -t main sp -c ./task/deploy-sql.yml -p deploy-sql -n
              fly -t main unpause-pipeline -p deploy-sql

