version: "3.4"

services:

  sql-server-db:
    image: microsoft/mssql-server-linux:2017-latest
    networks:
      - "traefik-net"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    deploy:
      labels:
        - "traefik.frontend.rule=Host:sql.${DNS_SUFFIX}"
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.enable=true"


networks:
  traefik-net:
    external: true


