version: "3.4"

services:
  sql-server-db:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - :1433
    networks:
      - "traefik-net"
    environment:
      SA_PASSWORD: "Password#1"
      ACCEPT_EULA: "Y"
    volumes:
      - sql-server-db:/var/lib/sql_server/data


volumes:
  sql-server-db:
    driver: rexray/scaleio
    driver_opts:
      size: 20

networks:
  traefik-net:
    external: true


